### ISSUE TITLE
Getting instance of text when added

### ISSUE THREAD

**Issue by Sulfkain** [burhanrashid52/PhotoEditor#142]
Hello,
As this issue https://github.com/burhanrashid52/PhotoEditor/issues/122
It will be helpfull to get the instance when adding/modify text.

Right now I need:
- The rootView to change the text with your api -editText(rootview, newText, color)-
- The TextView to set some style on runtime

It's maybe could be cheap just to pass a WeakReference of the view when added, so the consumer never will block that view or the photoEditor to be Garbage collector.

My use case is:
I have a custom editText where I can insert/change the text, the style or remove the text from this EditText.
And everything of this, will apply on the textView on PhotoEditor.
I need to show and hide the photoEditor textview too (the rootView in fact).
The style include, text size, color, gravity of the text, font family, and so on.

My workaround now it's looking for this views on the hierachy when added (on the listener of photoEditor) but it could break if you change something on the lib so I know it's dangerous and will be great to get some api to achieve this.

Any help you need on this, I could try to help you :)

Thanks!

**Comment by burhanrashid52** [comment]
Thanks, @Sulfkain Yeah sure. You can create a PR than we review it. If everything looks good we are good to merge.:)

**Comment by burhanrashid52** [comment]
Or if you want to discuss API before creating PR. We start the thread here.

**Comment by ashu2121** [comment]
Hey @Sulfkain,
Good after noon

did you take look into `editText` method present in  `PhotoEditor` class.  i think you can easily do some changes like adding some param to  `editText` like font name , size, color, other additional things. or you can make ArrayList and send all these things into one and retrieve into method and set TextView respectively. Do not forget to null checking,   additional param you are going to added in  `editText` method.

I think you can do easily. Let me know if you need further help
Thanks

**Comment by Sulfkain** [comment]
@ashu2121 that was the first I thought but it's almost impossible because the possibilities of style, always we miss someone and.. other user will request and so on.

I think the better will be pass the view to the customer and he do whatever he wants.

When I get some free time to look at this, I will try to look the code of PhotoEditor and try to create a PR about this, furthermore @burhanrashid52 what is your opinion to take action on this?
Because you told on other thread could be implemented on newer release, Have you thought already about this?

Thanks

**Comment by burhanrashid52** [comment]
I agreed with @Sulfkain on @ashu2121 Point.
I just planned to it do, but never got time to implement this. In short, I have not started it yet.
Although we have a discussion on [this](https://github.com/burhanrashid52/PhotoEditor/pull/108#issuecomment-442758790) with two approaches. My concern to the first approach is if we provide the view than the chances of breaking the library is more. Because we can't rely on the view attributes anymore inside our library. Since it can be changed anytime by the client.

**Comment by ashu2121** [comment]
Good Morning,
@burhanrashid52 is right returning view is not good idea @Sulfkain , If we return view to user than user can do anything with view and library will not able to retrieve attribute according to its functionality

According to thread you mentioned, Second approach is good, but in your library you to get all attribute of textview  so end result will look same as user EditText. 
I will check is there any method present and inform you back. 
thanks

**Comment by Sulfkain** [comment]
Hi, I will take a look on near future to the classes on the lib to see what is better way (in my opinion of course :D).

The 2 methods on the thread you mentioned @burhanrashid52 the second one, I think would be not enough to general purpose.
It's a great and clean solution but what you do with `editText` method? because it's not an new text, but a modification.
Could be clean and easy on lib just remove TextView child an replace with the new on, has no drawbacks on any part of the code?, that could be a solution.
Another little problem is what happens if you want the same textView but just changing the text color (f. ex) you need the old style to apply on the new TextView.

Maybe a solution could be a middle way, still can change the text with the actual method `editText(parentView, text, textColor)` and create a new one method like on the thread `addText/editText (myCustomizedTextView)`.

This is not perfect solution but cover almost any customized way.
Anyway, I will take a look on code to analyze all the possibilities :).

**Comment by Sulfkain** [comment]
I was this afternoon analysing the code of addText/editText.
The main point of this solutions is, clean, maintenable and simple code, so I avoided complicated solutions,

And I have arrived to 3 solutions:
- Retrieve the WeakReference(TextView) when `addText`.
You said @burhanrashid52 that changing some properties by client will break the lib, could you explain this? because any change on TextView should be reflected instanly on view.
The lib don't need to handle any property or I'm wrong?

- Create a new method to modify an actual textView, the method could be something like
`modifyText(rootView, myTextviewReplace)`.
The main problem I see on this solution is performance, if I the user modify the color, later the font, later the gravity and so on (UI user modify each property one by one, impossible to do a bulk update)
On each change, you should replace your old TextView with the new one, which raise memory preassure (1 delete 1 add) and garbage collector should run many times.
And the client should keep a instance of this temporal TextView to get the same style that the actual textView on the lib.

- Other solution could be adding `modifyText(rootView, gravity, font, color, size, etc...) `
As @ashu2121 said, but the problem is if we miss some style, we need to add it.
But this is simple and clean.

I prefer the first one, because the seems the simplest solution.
I don't like neither to pass a view to the client but seems the simplest solution for me.
But maybe I have not all the info and I miss something.

What do you think about it?
Thanks

**Comment by burhanrashid52** [comment]
First of all thanks for the detailed analysis. I don't like the 2nd approach either, so that is out of this solution. Initially, I thought the 1st solution would make more sense in terms of API but as we are mention it might to some unexpected changes from a client-side which might break the library. Let me discuss a few of them.
1. Overriding the library touch handler: From the [code](https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditor.java#L162) you can that we set our own multitouch and gesture listener to control the drag, pinch and click events from this class. If the client started to set there own touch listener than it might create an issue.
2.Tags: We set [tag](https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/main/java/ja/burhanrashid52/photoeditor/PhotoEditor.java#L149) on view to maintain the state of View selection. Client-side can change this one too.
3.Loading Html: Since TextView does a lot of stuff than just rendering text. One of them is it can load entire HTML content in `TextView` which we surely not expecting this in the library to have.

So the conclusion from my side is the solution 3 with builder seems safer to me. It's true there might be N number of attributes we need to add. But the thing is we don't know what kind of attributes developer want to customize. if we go with the builder approach develop can add extra attributes they like in the library manually. And if the number of request for that attribute is more we can add it into the library

**Comment by Sulfkain** [comment]
Perfect, then we agree to do the solution 3 due to be the cleanest, and with less headcaches.

I would try to do the PR this week (depending on free time...).

**Comment by burhanrashid52** [comment]
Cool.Thanks.Please try to add tests for it. I would really appreciated it.
