### ISSUE TITLE
Not working on android 10 and 10+ while save (Software rendering doesn't support hardware bitmaps)

### ISSUE THREAD

**Issue by br-neeraj** [burhanrashid52/PhotoEditor#277]
image not saved on android O and above, what to do

getting this error in Catch block - java.io.IOException: Operation not permitted

java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps

**Comment by ham3da** [comment]
I have this problem too.

**Comment by EzequielAdrianM** [comment]
You need to check if Android version code is **higher or equal to Q** then you **must** use [Scoped Storage](https://developer.android.com/about/versions/11/privacy/storage). This is a very dramatic change if favor of privacy since now, using scoped storage your app can only access some specific types of files, and will be able to create and access only its own created files without asking for storage permission. It's important to note that the app cannot access other's apps data.

Here is an example that may be useful:

```
//Is this Android 10+ and requires scoped storage?
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
    OutputStream outputStream;
    //Android 10+ already takes care of creating folders if don't exist.
    final String relativeLocation = Environment.DIRECTORY_PICTURES + File.separator + "PhotoEditor";
    ContentValues contentValues = new ContentValues();
    contentValues.put(MediaStore.MediaColumns.DISPLAY_NAME, "picture_name.jpg");
    contentValues.put(MediaStore.MediaColumns.MIME_TYPE, "image/jpeg");
    contentValues.put(MediaStore.MediaColumns.RELATIVE_PATH, relativeLocation);
    Uri uri = context.getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, contentValues);
    try {
        outputStream = context.getContentResolver().openOutputStream(uri);
        yourBitmapToSave.compress(Bitmap.CompressFormat.JPEG, 100, outputStream);
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    }
} else {
    //save the bitmap normally.. check if folder exists first.
}
```

**Comment by basitis** [comment]
@br-neeraj  and @ham3da  please let me know if this solution given by @EzequielAdrianM  helped you.

**Comment by burhanrashid52** [comment]
Added support for android 10/11 #365. Closing due to inacitivty
