### ISSUE TITLE
App crashes on Jelly Bean 4.2.2

### ISSUE THREAD

**Issue by ervinod** [burhanrashid52/PhotoEditor#31]
Hello there,
App crashes when i open ImageEditorActivity
Here is logcat error.... its related to font
Caused by: java.lang.RuntimeException: native typeface cannot be made
        at android.graphics.Typeface.<init>(Typeface.java:175)
        at android.graphics.Typeface.createFromAsset(Typeface.java:149)
        at com.enthuons.photoeditor.EditGalleryImageActivity.onCreate(EditGalleryImageActivity.java:144)

Can you please look into the issue.... On other versions i am not facing this issue but on JB 4.2.2 app get crashed

**Comment by burhanrashid52** [comment]
Are you using your own custom font and loading from assets? then this might help [Native typeface cannot be made](https://stackoverflow.com/questions/7531856/issue-when-using-a-custom-font-native-typeface-cannot-be-made)

**Comment by ervinod** [comment]
yes..... i am using one that you have put in assets folder
Typeface mEmojiTypeFace = Typeface.createFromAsset(getAssets(), "emojione-android.ttf");

getting error on this line
if i removed the code of custom font then app is working fine on JB 4.2.2 as well but emojis are displayed black colored

**Comment by burhanrashid52** [comment]
It's not a library issue. There is some issue with `emojione-android.ttf` file it's not backported to jelly bean. Try some other custom font it will work fine

**Comment by ervinod** [comment]
tried other font but not working.... still same error.... can u please look into issue on emulator with JB 4.2.2

**Comment by burhanrashid52** [comment]
I already did its working fine when i change the font. Try with `beyond_wonderland.ttf` font in sample app

**Comment by ervinod** [comment]
yes its working after setting font to beyond_wonderland.ttf but emoji's are not showing after setting this fot.... have you test it by adding emoji on image (JB 4.2.2).....
there is issue with smiley as well if i change font....please check this emoji  issue....

**Comment by burhanrashid52** [comment]
Emoji are render on the basis of custom or system fonts. Allowing custom font for emoji in the library is the reason to allow more customization to emoji rendering in case you have custom font specific to emoji.
The reason for black emoji is because the font you are providing that renders emoji's in black color.If you don't provide any font than emoji will be render on the basis of system fonts
More Info on emoji font check [EmojiCompact](https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat)
Closing this because this issue is related more to custom fonts for emoji
