### ISSUE TITLE
Image on photoeditorview is lost in split-screen mode

### ISSUE THREAD

**Issue by ervinod** [burhanrashid52/PhotoEditor#41]
Hello there,
Suppose i added image from gallery and start app in split-screen mode (multi-window mode). when app enters in split screen mode image on mPhotoEditorView is lost... just black screen is showing.
I face this issue on Android Oreo 8.0
Please test from your side and help me to solve this issue....

**Comment by ervinod** [comment]
Hello there...
Have you checked this issue....

**Comment by burhanrashid52** [comment]
Its happing due to activity is recreated every when going in multi-window mode. Currently, the library does not handle any lifecycle or configuration changes. You have handled all these changes where your activity resides.
To start with you need to disable the cycle event by handling configuration manually.
This great article will help you
https://medium.com/google-developers/5-tips-for-preparing-for-multi-window-in-android-n-7bed803dda64

**Comment by burhanrashid52** [comment]
On a side **Note** even if you handle config changes than there will be an issue of paints positions and size of added emoji and stickers.
I recommend you to not use multi-window of this library. Because it does not make sense to edit an image in a smaller window
