### ISSUE TITLE
Image saving with borders 

### ISSUE THREAD

**Issue by xee95** [burhanrashid52/PhotoEditor#42]
when i save image if image height is low than auto black border is added into it and if width is low then auto black border is added .

can you please help me ?

**Comment by yooneskh** [comment]
i also have this problem

**Comment by burhanrashid52** [comment]
This is happening due to `BitmapUtil.removeTransparency(parentView.getDrawingCache());` while saving image.I need to work on the transparency logic. But for now, if you want to have the transparency in your image than you can remove this method `BitmapUtil.removeTransparency()` and use `parentView.getDrawingCache()` directly like this

```
  parentView.setDrawingCacheEnabled(true);
  Bitmap drawingCache =parentView.getDrawingCache();
  drawingCache.compress(Bitmap.CompressFormat.PNG, 100, out);
```

**Comment by xee95** [comment]
Works fine when using "wrap_content" otherwise show black border. 

` <ja.burhanrashid52.photoeditor.PhotoEditorView
        android:id="@+id/photoEditorView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

    </ja.burhanrashid52.photoeditor.PhotoEditorView>`

**Comment by burhanrashid52** [comment]
Is this issue got resolved? @xee95 @yooneskh

**Comment by burhanrashid52** [comment]
Now you can set options while saving the image.
Resolved in v.0.3.2
For more details check Saving [Wiki](https://github.com/burhanrashid52/PhotoEditor/wiki/Saving)
