### ISSUE TITLE
Using DataBinding in Sample app

### ISSUE THREAD

**Issue by burhanrashid52** [burhanrashid52/PhotoEditor#435]
- [ ] ~~Use data binding to bind views in the sample app.~~
- [x] Remove necessary null values.
- [x] Use lateinit.

**Comment by wasky** [comment]
Second and third tasks from the list are resolved in #494

**Comment by wasky** [comment]
My personal opinion is that sample app should not use data binding / view binding:

* Sample should be as simple as possible, easy to understand also for those who are not using data binding / view binding.
* Data binding increases build time (probably not a big issue because the project is rather small).
* There's Jetpack Compose on the horizon, so probably in the future it will be better to migrate sample app to Compose rather than integrate data binding / view binding.

**Comment by burhanrashid52** [comment]
> My personal opinion is that sample app should not use data binding / view binding:
> 
>     * Sample should be as simple as possible, easy to understand also for those who are not using data binding / view binding.
> 
>     * Data binding increases build time (probably not a big issue because the project is rather small).
> 
>     * There's Jetpack Compose on the horizon, so probably in the future it will be better to migrate sample app to Compose rather than integrate data binding / view binding.

Make sense. Closing the issue.
