### ISSUE TITLE
Index out of bound

### ISSUE THREAD

**Issue by hoangtuancntt** [burhanrashid52/PhotoEditor#445]
Sometime I got an error Indexout of bound : index1 size 0 when save image. how do I solve this bug ?

**Comment by lucianocheng** [comment]
@hoangtuancntt do you have a stacktrace we can look at from the crash?

**Comment by lucianocheng** [comment]
If this is happening sporadically, it may be because a user is adding / removing an element while the editor is saving.

Currently we export the image by reading directly from the View Tree on a AsyncTask background task. If the view tree is changed and not flushed, it can create an inconsistent state.

We don't have a good way to "copy" the view tree before exporting, and we don't want to run the export on the main (UI) thread, so we don't have a great solution for this at the moment.

A good workaround would be to disallow a user from changing anything in the editor while PhotoSaverTask is running.

Eventually we should probably not be reading from the View Tree for export. See #10
