### ISSUE TITLE
Brush color changes after saving image...

### ISSUE THREAD

**Issue by ervinod** [burhanrashid52/PhotoEditor#52]
Hello there... 
I found one bug when using brush....
Suppose i draw something on view in one color and again  i draw something using brush in other color (overlapping first one), when we save image brush color automatically changes.
Please refer following screenshots.
Before saving....
![img_20180612_114927](https://user-images.githubusercontent.com/25130073/41274564-785e5e96-6e3b-11e8-9e37-a553a7c00154.jpg)
After saving image(red color automatically changes to navy blue)
![img_20180612_114901](https://user-images.githubusercontent.com/25130073/41274586-8b1542b6-6e3b-11e8-807c-4f4a42f8e8df.jpg)
Please check this bug.....

**Comment by ervinod** [comment]
Hello sir, when this bug is expected to resolve

**Comment by ervinod** [comment]
Hello there... when this bug is expected to resolve ?

**Comment by Sulfkain** [comment]
The problem seems the PorterDuffxDeff on drawing
`mDrawPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.DARKEN));`
on line 78 on `BrushDrawingView.java` file

I didn't modify the mode to check it but I was trying to figure out where the problem is, and it not from compress function, nor removeTransparent function, nor the opacity of the line

And only apply to line draws so, it almot sure that's the problem.
Change it to the default (comment the line) and try it

**Comment by burhanrashid52** [comment]
Thank a lot @Sulfkain I was looking for the solution for days.
@ervinod I have fixed issue on dev branch and will release a new version with multiple bug fixes.

**Comment by ervinod** [comment]
Thanks for resolving this issue.... waiting for next release with other remaining bug fixes

**Comment by Sulfkain** [comment]
@burhanrashid52 
Hey!, I was working on that fix too, and today I have found something weird.
Are you sure this fix works allways, because I'm seeing that some draws do the same _darken_ blender :S

<img width="265" alt="captura de pantalla 2018-07-30 a las 9 53 39" src="https://user-images.githubusercontent.com/17082246/43384563-b69da6bc-93de-11e8-9c8b-cc5d245a5d8c.png">

All paths works but not the light blue :S, eraser works.
The only full working solution i found was to change the acceleration type (and maybe that mess up the eraser)
If you change to a Software acceleration instead of hardware acceleration, that seems to work.

**Comment by burhanrashid52** [comment]
I have tested on a few devices the with 3-4 colors only. Need to check with light blue color.
That's true if you change acceleration type than eraser won't work, changing the acceleration type was one of my solutions to make eraser work.

**Comment by Sulfkain** [comment]
Seem to fail with some light color paths, when overlay other paths darker. 
Not only with the light blue.
It's really weird :s

**Comment by haniha** [comment]
same problem here with light colors
any idea why the light colors ?!

**Comment by burhanrashid52** [comment]
Currently, don't have any idea. Working on it

**Comment by burhanrashid52** [comment]
Resolved v.0.3.1

**Comment by Sulfkain** [comment]
@burhanrashid52 I have checked and everything working fine! perfect.
Just curious, What was de problem?
Thx for this release!

**Comment by burhanrashid52** [comment]
I really don't know. I made the changes as you mentioned and tested with 4 devices and its worked fine. So I thought it might be the device specific issue. It's really weird.
